apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandboxed-agent
spec:
  replicas: 2  # horizontal scaling
  selector:
    matchLabels:
      app: sandboxed-agent
  template:
    metadata:
      labels:
        app: sandboxed-agent
    spec:
      containers:
        - name: agent
          image: sandboxed-agent:latest
          ports:
            - containerPort: 8000 # API
            - containerPort: 6080 # noVNC
          securityContext:
            privileged: true  # required for Firecracker
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: sandboxed-agent
spec:
  selector:
    app: sandboxed-agent
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: novnc
      port: 6080
      targetPort: 6080
  type: LoadBalancer 